baseURL = "https://suzusky.net/"
languageCode = "ja"
title = "Suzusky"
theme = "PaperMod"

enableEmoji = true
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[permalinks]
  posts = "/:year/:slug/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  author = "Ryotaro SUMI"
  description = "suzusky : @ryo_628's homepage"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "Ryotaro SUMI"
    subtitle = "@ryo_628's homepage"
    imageUrl = "https://avatars2.githubusercontent.com/u/13991840"
    imageWidth = 120
    imageHeight = 120

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ryo628"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/ryo_628"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:ryo@suzusky.net"
