services:
  hugo_app:
    container_name: hugo_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: ${GO_VERSION}
        HUGO_VERSION: ${HUGO_VERSION}
    ports:
      - 1313:1313
    tty: true
    volumes:
      - ./hugo:/hugo
    working_dir: /hugo
    command: hugo server -D --bind="0.0.0.0"
